version: '3.9'

services:
  web:
    build: .
    volumes: 
      - .:/app
    # ports:
    #   - 8080:8080
    ports:
      - "8000:8000"
    container_name : web
    depends_on:
      - db
      - redis
    


  # db:
  #   image: postgres:latest
  #   container_name: goRoute-postgres
  #   # env_file:
  #   #   - .env
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=goroute_pjt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
   

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:




